<template>
	<section class="collage">
		<h2 class="collage__type" aria-hidden="true">Ortiz<br />Metals</h2>

		<div class="collage__grid">
			<figure ref="featureEl" class="feature">
				<picture>
					<source type="image/avif" :srcset="srcset(feature.base, 'avif')" :sizes="featSizes" />
					<source type="image/webp" :srcset="srcset(feature.base, 'webp')" :sizes="featSizes" />
					<img
						ref="featureImg"
						:src="`${feature.base}-900.jpg`"
						:srcset="srcset(feature.base, 'jpg')"
						:sizes="featSizes"
						:alt="feature.desc"
						fetchpriority="high"
						decoding="async"
					/>
				</picture>
				<figcaption>
					<span class="feature__tag">Selected Work — {{ pad(featureIndex + 1) }}</span>
					<strong>{{ feature.holder }}</strong>
					<span class="feature__desc">{{ feature.desc }}</span>
					<span class="feature__year">{{ feature.year }}</span>
				</figcaption>
			</figure>

			<button
				v-for="tile in tiles"
				:key="tile.img.index"
				type="button"
				class="tile"
				@click="select(tile.i)"
			>
				<picture>
					<source type="image/avif" :srcset="srcset(tile.img.base, 'avif')" :sizes="tileSizes" />
					<source type="image/webp" :srcset="srcset(tile.img.base, 'webp')" :sizes="tileSizes" />
					<img
						:src="`${tile.img.base}-450.jpg`"
						:srcset="srcset(tile.img.base, 'jpg')"
						:sizes="tileSizes"
						:alt="tile.img.desc"
						loading="lazy"
						decoding="async"
					/>
				</picture>
				<span class="tile__label">{{ tile.img.holder }}</span>
			</button>
		</div>

		<p class="collage__foot">
			<span>{{ pad(images.length) }} works</span>
			<span>Sculpture · Architectural · Public</span>
		</p>
	</section>
</template>

<script setup>
	import { computed, nextTick, onMounted, ref } from 'vue';
	import { useHead } from '@unhead/vue';
	import gsap from 'gsap';
	import gallery from '@/gallery.json';

	// Flatten each work's caption onto the work so the template keeps using
	// img.base / img.holder / img.desc / img.year (index = stable render order).
	const images = gallery.works.map((work) => ({
		index: work.order,
		base: work.base,
		holder: work.caption.holder,
		desc: work.caption.desc,
		year: work.caption.year,
	}));

	useHead({
		title: 'Ortiz Metals — Custom Sculpture & Metalwork | Randy Ortiz, Eugene OR',
		meta: [
			{
				name: 'description',
				content:
					'Custom sculpture, architectural metalwork, and site-specific public art by Randy Ortiz, a Eugene, Oregon based artist.',
			},
		],
	});

	const featureIndex = ref(0);
	const featureImg = ref(null);
	const featureEl = ref(null);

	const feature = computed(() => images[featureIndex.value] || {});
	const tiles = computed(() =>
		images.map((img, i) => ({ img, i })).filter((t) => t.i !== featureIndex.value)
	);
	const pad = (n) => String(n).padStart(2, '0');

	// responsive image helpers (variants generated by scripts/optimize-images.mjs)
	const srcset = (base, ext) => `${base}-450.${ext} 450w, ${base}-900.${ext} 900w`;
	const featSizes = '(max-width: 820px) 92vw, 56vw';
	const tileSizes = '(max-width: 820px) 46vw, 22vw';

	// slow, living "breath" on the hero so it never feels static
	let drift = null;
	function startDrift() {
		if (drift) drift.kill();
		if (!featureImg.value) return;
		if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
		drift = gsap.fromTo(
			featureImg.value,
			{ scale: 1 },
			{ scale: 1.06, duration: 9, ease: 'sine.inOut', yoyo: true, repeat: -1 }
		);
	}

	function select(i) {
		if (i === featureIndex.value) return;
		featureIndex.value = i;
		nextTick(() => {
			if (drift) drift.kill();
			if (featureImg.value) {
				gsap.fromTo(
					featureImg.value,
					{ clipPath: 'inset(0 0 0 100%)', scale: 1.12 },
					{
						clipPath: 'inset(0 0 0 0%)',
						scale: 1,
						duration: 0.8,
						ease: 'power4.out',
						onComplete: startDrift,
					}
				);
			}
			// On mobile the feature sits above the tiles — bring the swapped work into view.
			if (window.matchMedia('(max-width: 820px)').matches && featureEl.value) {
				featureEl.value.scrollIntoView({ behavior: 'smooth', block: 'start' });
			}
		});
	}

	onMounted(() => {
		const tl = gsap.timeline({ delay: 0.15 });

		tl.fromTo(
			'.collage__type',
			{ yPercent: 18, opacity: 0 },
			{ yPercent: 0, opacity: 0.07, duration: 1.2, ease: 'power4.out' },
			0
		)
			// hero wipes in from the right edge while the image settles out of an overscale
			.fromTo(
				'.feature',
				{ clipPath: 'inset(0 0 0 100%)' },
				{ clipPath: 'inset(0 0 0 0%)', duration: 1, ease: 'power4.out' },
				0.1
			)
			.fromTo(
				'.feature img',
				{ scale: 1.2 },
				{ scale: 1, duration: 1.4, ease: 'power3.out', onComplete: startDrift },
				0.1
			)
			// tiles cascade in after the hero is established
			.fromTo(
				'.collage .tile',
				{ y: 40, opacity: 0, clipPath: 'inset(0 0 100% 0)' },
				{
					y: 0,
					opacity: 1,
					clipPath: 'inset(0 0 0% 0)',
					duration: 0.85,
					stagger: 0.08,
					ease: 'power3.out',
				},
				0.5
			);
	});
</script>

<style scoped lang="scss">
	.collage {
		position: relative;
		width: min(1500px, 100%);
		margin: 0 auto;
		padding: clamp(1.5rem, 4vw, 3rem) clamp(1rem, 4vw, 3rem) clamp(2rem, 4vw, 3rem);
		min-height: calc(100vh - 12rem);
		isolation: isolate;
	}

	.collage__type {
		position: absolute;
		top: clamp(-1rem, -1vw, 0rem);
		right: clamp(1rem, 4vw, 3rem);
		z-index: -1;
		margin: 0;
		font-family: var(--font-antonio);
		text-transform: uppercase;
		text-align: right;
		line-height: 0.78;
		font-size: clamp(6rem, 22vw, 22rem);
		color: var(--bone);
		opacity: 0.07;
		pointer-events: none;
	}

	.collage__grid {
		display: grid;
		grid-template-columns: repeat(12, 1fr);
		grid-auto-rows: clamp(3.4rem, 6.2vh, 5.4rem);
		gap: clamp(0.5rem, 1vw, 0.9rem);
	}

	picture {
		display: contents;
	}

	.feature {
		position: relative;
		grid-column: 1 / 8;
		grid-row: 1 / 8;
		margin: 0;
		overflow: hidden;
		border: 1px solid var(--line);
		box-shadow: 0 40px 110px rgba(0, 0, 0, 0.5);

		img {
			width: 100%;
			height: 100%;
			object-fit: cover;
			will-change: clip-path, transform;
		}

		figcaption {
			position: absolute;
			left: 0;
			bottom: 0;
			right: 0;
			display: grid;
			grid-template-columns: 1fr auto;
			gap: 0.1rem 1rem;
			padding: clamp(1rem, 2vw, 1.6rem);
			background: linear-gradient(to top, rgba(10, 7, 6, 0.92), transparent);
		}

		&__tag {
			grid-column: 1 / -1;
			font-family: var(--font-antonio);
			text-transform: uppercase;
			letter-spacing: 0.16em;
			font-size: 0.72rem;
			color: var(--ember);
			margin-bottom: 0.4rem;
		}

		strong {
			grid-column: 1;
			font-family: var(--font-antonio);
			text-transform: uppercase;
			font-weight: 500;
			font-size: clamp(1.8rem, 3.5vw, 3rem);
			line-height: 0.95;
			color: var(--bone);
		}

		&__desc {
			grid-column: 1;
			font-family: Georgia, serif;
			font-style: italic;
			color: rgba(255, 233, 211, 0.75);
		}

		&__year {
			grid-column: 2;
			grid-row: 2 / 4;
			align-self: end;
			font-family: var(--font-antonio);
			font-size: clamp(1.8rem, 3vw, 2.6rem);
			color: var(--ember);
		}
	}

	.tile {
		position: relative;
		overflow: hidden;
		padding: 0;
		border: 1px solid var(--line);
		background: var(--ink);
		cursor: pointer;

		img {
			width: 100%;
			height: 100%;
			object-fit: cover;
			transition: transform 0.6s cubic-bezier(0.16, 1, 0.3, 1), filter 0.4s ease;
			filter: grayscale(0.35) brightness(0.82);
		}

		&__label {
			position: absolute;
			left: 0.6rem;
			bottom: 0.5rem;
			font-family: var(--font-antonio);
			text-transform: uppercase;
			font-size: 0.78rem;
			color: var(--bone);
			opacity: 0;
			transform: translateY(0.4rem);
			transition: opacity 0.35s ease, transform 0.35s ease;
		}

		&:hover img {
			transform: scale(1.08);
			filter: grayscale(0) brightness(1);
		}

		&:hover .tile__label {
			opacity: 1;
			transform: translateY(0);
		}

		// asymmetric placement — deterministic collage for the 7 non-feature tiles
		&:nth-of-type(1) { grid-column: 8 / 13; grid-row: 1 / 4; }
		&:nth-of-type(2) { grid-column: 8 / 11; grid-row: 4 / 8; }
		&:nth-of-type(3) { grid-column: 11 / 13; grid-row: 4 / 6; }
		&:nth-of-type(4) { grid-column: 11 / 13; grid-row: 6 / 8; }
		&:nth-of-type(5) { grid-column: 1 / 4; grid-row: 8 / 12; }
		&:nth-of-type(6) { grid-column: 4 / 8; grid-row: 8 / 12; }
		&:nth-of-type(7) { grid-column: 8 / 13; grid-row: 8 / 12; }
	}

	.collage__foot {
		display: flex;
		justify-content: space-between;
		gap: 1rem;
		margin-top: 1.2rem;
		font-family: var(--font-antonio);
		text-transform: uppercase;
		letter-spacing: 0.12em;
		font-size: 0.8rem;
		color: rgba(255, 233, 211, 0.55);
	}

	/* ---- Tablet: feature on top, tiles in a balanced grid ---- */
	@media (max-width: 820px) {
		.collage {
			min-height: auto;
		}

		.collage__type {
			position: static;
			text-align: left;
			margin-bottom: 0.5rem;
			font-size: clamp(3.5rem, 16vw, 7rem);
			opacity: 0.12;
		}

		.collage__grid {
			grid-template-columns: repeat(4, 1fr);
			grid-auto-rows: auto;
		}

		.feature {
			grid-column: 1 / -1;
			grid-row: auto;
			aspect-ratio: 4 / 3;
		}

		.tile {
			grid-column: span 2 !important;
			grid-row: auto !important;
			aspect-ratio: 4 / 3;

			img {
				filter: none;
			}

			&__label {
				opacity: 1;
				transform: none;
				background: linear-gradient(to top, rgba(10, 7, 6, 0.85), transparent);
				left: 0;
				right: 0;
				bottom: 0;
				padding: 1.4rem 0.6rem 0.5rem;
			}
		}
	}

	/* ---- Phone: full-bleed feature, two-up tiles ---- */
	@media (max-width: 520px) {
		.collage {
			padding: 1rem 1rem 2rem;
		}

		.feature {
			aspect-ratio: 3 / 4;
		}

		.feature strong {
			font-size: clamp(1.6rem, 7vw, 2.2rem);
		}

		.collage__foot {
			flex-direction: column;
			gap: 0.3rem;
		}
	}
</style>
